name: Linux, gcc, EDK2

on:
  push:
  workflow_dispatch: 

env:
  COMPILER: GCC5
  BUILD_TYPES: RELEASE
  FULL_SHELL_GUID: EA4BB293-2D7F-4456-A681-1F22F42CD0BC
  ARCH: X64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install toolchains
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install gcc nasm uuid-dev build-essential

    - name: Set up EDK2
      run: make -C edk2/BaseTools

    - name: Build UEFI binaries
      run: |
        cd edk2
        source edksetup.sh
        build -a ${{ env.ARCH }} -b RELEASE -t ${{ env.COMPILER }} -p ShellPkg/ShellPkg.dsc

    - name: Create individual Shell binaries
      run: |
        cp edk2/Build/Shell/RELEASE_${{ env.COMPILER }}/${{ env.ARCH }}/Shell_${{ env.FULL_SHELL_GUID }}.efi ./ShellX64.efi

    - name: Display SHA-256
      run: |
        sha256sum *.efi

    - name: Upload artifact
      uses: actions/upload-artifact@v5
      with:
        name: UEFI-Shell-X64
        path: ShellX64.efi
